version: '3.7'
services:
  vue-service:
    image: vue-service
    build:
      dockerfile: docker/node/Dockerfile
      context: ../.
    volumes:
      - ../front:/home/node:delegated
    ports:
      - 8080:8080
    environment:
      - HOSTNAME=localhost
      - VHOST=vue-behaviour